export enum EnumSignalRType {
    LOG_IN = "LOG_IN",
    ENTITY_CHANGED = "ENTITY_CHANGED",
    ACTIVITY = "ACTIVITY",
    ACTIVITY_HISTORY_RESET = 'ACTIVITY_HISTORY_RESET',
    TASK_PROGRESS = "TASK_PROGRESS",
}