import { Navigation } from "../_models/index";

export const navigationSystem: Navigation[] = [
  {
    id: "sys_dashboard",
    title: "Tổng quan",
    translate: "Tổng quan",
    type: "item",
    icon: "home",
    url: "/sys/sdashboard",
    children: [],
  },
  {
    id: "sys_config",
    title: "Hệ thống",
    translate: "NAV_SYSTEM.USERS",
    type: "group",
    icon: "gear",
    url: "/sys/config",
    children: [
      {
        id: "sys_groupfunction",
        title: "Nhóm chức năng",
        translate: "Nhóm chức năng",
        type: "item",
        url: "/sys/config/groupfunction",
        exactMatch: true, children: [],
      },
      {
        id: "sys_function",
        title: "Chức năng",
        translate: "Chức năng",
        type: "item",
        url: "/sys/config/function",
        exactMatch: true, children: [],
      },
      {
        id: "sys_module",
        title: "Module",
        translate: "Module",
        type: "item",
        url: "/sys/config/module",
        exactMatch: true, children: [],
      },

      {
        id: "sys_package",
        title: "Package",
        translate: "Package",
        type: "item",
        url: "/sys/config/syspackage",
        exactMatch: true, children: [],
      },
      {
        id: "sys_groupuser",
        title: "Nhóm tài khoản",
        translate: "Nhóm tài khoản",
        type: "item",
        url: "/sys/config/groupuser",
        exactMatch: true, children: [],
      },
      {
        id: "sys_user",
        title: "Tài khoản",
        translate: "Tài khoản",
        type: "item",
        url: "/sys/config/user",
        exactMatch: true, children: [],
      },
      {
        id: "sys_user",
        title: "Phân quyền nhóm tài khoản",
        translate: "Phân quyền nhóm tài khoản",
        type: "item",
        url: "/sys/config/groupuserpermission",
        exactMatch: true, children: [],
      },
      {
        id: "sys_user",
        title: "Phân quyền Tài khoản",
        translate: "Phân quyền Tài khoản",
        type: "item",
        url: "/sys/config/userpermission",
        exactMatch: true,
        children: [],
      }
    ],
  },
  {
    id: "sys_customer",
    title: "Khách hàng",
    translate: "Khách hàng",
    type: "group",
    icon: "gear",
    url: "/sys/customer",
    children: [
      {
        id: "sys_customer",
        title: "Quản lý khách hàng",
        translate: "Quản lý khách hàng",
        type: "item",
        url: "/sys/config/tenant",
        exactMatch: true, children: [],
      },
      {
        id: "sys_tenantcontract",
        title: "Quản lý hợp đồng",
        translate: "Quản lý hợp đồng",
        type: "item",
        url: "/sys/config/tenantcontract",
        exactMatch: true,
        children: [],
      }
    ],
  },
  {
    id: "sys_website",
    title: "Website",
    translate: "Website",
    type: "group",
    icon: "gear",
    url: "/sys/website",
    children: [
      {
        id: "sys_category",
        title: "Danh mục tin",
        translate: "Danh mục tin",
        type: "item",
        url: "/sys/website/category",
        exactMatch: true, children: [],
      },
      {
        id: "sys_blog",
        title: "Tin tức",
        translate: "Tin tức",
        type: "item",
        url: "/sys/website/blog",
        exactMatch: true, children: [],
      },
      {
        id: "sys_themeblog",
        title: "Chủ đề",
        translate: "Chủ đề",
        type: "item",
        url: "/sys/website/themeblog",
        exactMatch: true, children: [],
      },
      {
        id: "sys_contract",
        title: "Thông tin liên hệ",
        translate: "Thông tin liên hệ",
        type: "item",
        url: "/sys/website/contract",
        exactMatch: true,
        children: [],
      }
    ],
  },
  {
    id: "sys_otherlist",
    title: "Danh mục",
    translate: "Danh mục",
    type: "group",
    icon: "home",
    children: [
      {
        id: "sys_otherlist",
        title: "Danh mục dùng chung",
        translate: "Danh mục dùng chung",
        type: "item",
        url: "/sys/listsys/otherlist",
        exactMatch: true, children: [],
      },
      {
        id: "sys_bank",
        title: "Danh mục ngân hàng",
        translate: "Danh mục ngân hàng",
        type: "item",
        url: "/sys/listsys/bank",
        exactMatch: true, children: [],
      },
    ]

  },
  {
    id: "sys_config",
    title: "Thiết lập",
    translate: "Thiết lập",
    type: "group",
    icon: "home",
    children: [
      {
        id: "sys_gohr",
        title: "Bộ dữ liệu mẫu",
        translate: "Bộ dữ liệu mẫu",
        type: "group",
        children: [
          {
            id: "sys_symbolsys",
            title: "Ký hiệu công",
            translate: "Ký hiệu công",
            type: "item",
            url: "/sys/configsys/symbolsys",
            exactMatch: true, children: [],
      },
          {
            id: "sys_timetype",
            title: "kiểu công",
            translate: "kiểu công",
            type: "item",
            url: "/sys/configsys/timetype",
            exactMatch: true, children: [],
      },
          {
            id: "sys_grouppositionsys",
            title: "Nhóm chức danh",
            translate: "Nhóm chức danh",
            type: "item",
            url: "/sys/configsys/grouppositionsys",
            exactMatch: true, children: [],
      },
          {
            id: "sys_positionsys",
            title: "Chức danh",
            translate: "Chức danh",
            type: "item",
            url: "/sys/configsys/positionsys",
            exactMatch: true, children: [],
      },
          {
            id: "sys_contracttypesys",
            title: "Loại hợp đồng",
            translate: "Loại hợp đồng",
            type: "item",
            url: "/sys/configsys/contracttypesys",
            exactMatch: true, children: [],
      },
          {
            id: "sys_shiftsys",
            title: "Ca làm việc",
            translate: "Ca làm việc",
            type: "item",
            url: "/sys/configsys/shiftsys",
            exactMatch: true, children: [],
      },
          {
            id: "sys_salarytypesys",
            title: "Bảng lương",
            translate: "Bảng lương",
            type: "item",
            url: "/sys/configsys/salarytypesys",
            exactMatch: true,
            children: [],
          },
          {
            id: "sys_salaryelementsys",
            title: "Phần thử lương",
            translate: "phần thử lương",
            type: "item",
            url: "/sys/configsys/salaryelementsys",
            exactMatch: true,
            children: [],
          },
          {
            id: "sys_salarystructuresys",
            title: "Thông tin kết cấu bảng lương",
            translate: "Thông tin kết cấu bảng lương",
            type: "item",
            url: "/sys/configsys/salarystructuresys",
            exactMatch: true,
            children: [],
          },
          {
            id: "sys_spayrollformulasys",
            title: "Công thức tính lương",
            translate: "Công thức tính lương",
            type: "item",
            url: "/sys/configsys/payrollformulasys",
            exactMatch: true,
            children: [],
          },
          {
            id: "sys_settingreportsys",
            title: "Thiết lập mẫu báo cáo",
            translate: "Thiết lập mẫu báo cáo",
            type: "item",
            url: "/sys/configsys/settingreportsys",
            exactMatch: true,
            children: [],
          }
        ]
      }
    ]
  },
];
