import { Navigation } from "../_models/index";

export const navigation: Navigation[] = [
  {
    id: "cms_organize",
    title: "Tổ chức",
    translate: "Tổ chức",
    type: "group",
    icon: "home",
    url: "/cms/organize",
    root: true,
    children: [
      {
        id: "organize_dashboard",
        title: "Dashboard",
        translate: "Dashboard",
        type: "group",
        icon: "users",
        url: "/cms/organize/dashboarddetail",
        children: [
          {
            id: "org_dashboard",
            title: "Tổng quan công việc",
            translate: "Tổng quan công việc",
            type: "item",
            url: "/cms/organize/dashboarddetail/dashboardposition",
            exactMatch: true,
            children: []
          },
        ],
      },
      {
        id: "organize_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/cms/organize/business",
        children: [
          {
            id: "org_struct",
            title: "Cơ cấu tổ chức",
            translate: "Cơ cấu tổ chức",
            type: "item",
            url: "/cms/organize/business/organization-struct",
            exactMatch: true,
            children: [],
          },
          {
            id: "org_job",
            title: "Công việc",
            translate: "Công việc",
            type: "item",
            url: "/cms/organize/business/job",
            exactMatch: true,
            children: [],
          },
          {
            id: "org_position",
            title: "Vị trí",
            translate: "Vị trí",
            type: "item",
            url: "/cms/organize/business/position",
            exactMatch: true,
            children: [],
          },
          {
            id: "org_plan",
            title: "Hoạch định",
            translate: "Hoạch định",
            type: "item",
            url: "/cms/organize/business/plan",
            exactMatch: true,
            children: [],
          },
          {
            id: "organization",
            title: "Khai báo cơ cấu tổ chức",
            translate: "Khai báo cơ cấu tổ chức",
            type: "item",
            url: "/cms/organize/business/organization",
            exactMatch: true,
            children: [],
          },
          {
            id: "position",
            title: "Chức danh",
            translate: "Chức danh",
            type: "item",
            url: "/cms/organize/list/position",
            exactMatch: true,
            children: [],
          }
        ],
      },
      {
        id: "organize_report",
        title: "Báo cáo",
        translate: "Báo cáo",
        type: "group",
        icon: "gear",
        url: "/cms/organize/report",
        children: [
          {
            id: "org_report",
            title: "Báo cáo biểu đồ",
            translate: "Báo cáo biểu đồ",
            type: "item",
            url: "/cms/organize/report/reports",
            exactMatch: true,
            children: [],
          },
        ],
      },
      {
        id: "cms_organize_list",
        title: "Danh mục",
        translate: "NAV.LIST",
        type: "group",
        icon: "list",
        url: "/cms/organize/list",
        children: [
          {
            id: "organize_list_job-band",
            title: "Danh mục cấp bậc",
            translate: "Danh mục cấp bậc",
            type: "item",
            url: "/cms/organize/list/job-band",
            exactMatch: true,
            children: [],
          },
          {
            id: "companyinfo",
            title: "Thông tin công ty",
            translate: "Thông tin công ty",
            type: "item",
            url: "/cms/organize/list/companyinfo",
            exactMatch: true,
            children: [],
          },
          {
            id: "job",
            title: "Danh mục công việc",
            translate: "Danh mục công việc",
            type: "item",
            url: "/cms/organize/list/job",
            exactMatch: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_profile",
    title: "Hồ sơ",
    translate: "Hồ sơ",
    type: "group",
    icon: "gear",
    url: "/cms/profile",
    root: true,
    children: [
      {
        id: "cms_staff",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/cms/profile/business",
        children: [
          {
            id: "staff_profile",
            title: "Hồ sơ nhân viên",
            translate: "NAV.STAFF_LIST.STAFFPROFILE",
            type: "item",
            url: "/cms/profile/business/staffprofile",
            exactMatch: true,
            children: [],
          },
          {
            id: "decision",
            title: "Quyết định thay đổi thông tin nhân sự",
            translate: "Quyết định thay đổi thông tin nhân sự",
            type: "item",
            url: "/cms/profile/business/decision",
            exactMatch: true,
            children: [],
          },
          {
            id: "contractinfor",
            title: "Thông tin hợp đồng",
            translate: "Thông tin hợp đồng",
            type: "item",
            url: "/cms/profile/business/contractinfor",
            exactMatch: true,
            children: [],
          },

          {
            id: "commend",
            title: "Thông tin khen thưởng",
            translate: "Thông tin khen thưởng",
            type: "item",
            url: "/cms/profile/business/commend",
            exactMatch: true,
            children: [],
          },
          {
            id: "discipline",
            title: "Thông tin kỷ luật",
            translate: "Thông tin kỷ luật",
            type: "item",
            url: "/cms/profile/business/discipline",
            exactMatch: true,
            children: [],
          },
          {
            id: "leavejob",
            title: "Thông tin nghỉ việc",
            translate: "Thông tin nghỉ việc",
            type: "item",
            url: "/cms/profile/business/leavejob",
            exactMatch: true,
            children: [],
          },
          {
            id: "candidatescancv",
            title: "Scan CV",
            translate: "Scan CV",
            type: "item",
            url: "/cms/profile/business/candidatescancv",
            exactMatch: true,
            children: [],
          },
          // {
          //   id: "angular-tree-grid",
          //   title: "Cơ cấu tổ chức",
          //   translate: "Cơ cấu tổ chức",
          //   type: "item",
          //   url: "/cms/profile/business/angular-tree-grid",
          //   exactMatch: true,
          // },
          // {
          //   id: "cms_timekeepingreport",
          //   title: "Báo cáo chấm công",
          //   translate: "NAV.STAFF_LIST.TIMEKEEPINGREPORT",
          //   type: "group",
          //   exactMatch: true,
          //   children: [
          //     {
          //       id: "cms_member_report",
          //       title: "Danh sách nhân viên đi muộn về sớm và nghỉ",
          //       translate: "NAV.STAFF_LIST.MEMBERREPORT",
          //       type: "item",
          //       url: "/cms/staff/memberreport",
          //       exactMatch: true,
          //     },
          //     {
          //       id: "cms_total_report",
          //       title: "Báo cáo tổng hợp số ngày nghỉ của nhân viên",
          //       translate: "NAV.STAFF_LIST.TOTALREPORT",
          //       type: "item",
          //       url: "/cms/staff/totalreport",
          //       exactMatch: true,
          //     },
          //   ],
          // },
        ],
      },
      {
        id: "cms_profile_setting1",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/cms/profile/setting",
        children: [
          {
            id: "orgchart",
            title: "Cây sơ đồ tổ chức",
            translate: "NAV.LIST_LIST.ORG_CHART",
            type: "item",
            url: "/cms/profile/setting/orgchart",
            exactMatch: true,
            children: [],
          },
          {
            id: "allowanseemployee",
            title: "Phụ cấp nhân viên",
            translate: "Phụ cấp nhân viên",
            type: "item",
            url: "/cms/profile/list/allowanseemployee",
            exactMatch: true,
            children: [],
          },
          {
            id: "cms_pospaper",
            title: "Giấy tờ theo chức vụ",
            translate: "Giấy tờ theo chức vụ",
            type: "item",
            url: "/cms/profile/setting/pospaper",
            exactMatch: true,
            children: [],
          },
          {
            id: "cms-app-decisioncreate",
            title: "Thiết lập quy tắc sinh số quyết định",
            translate: "Thiết lập quy tắc sinh số quyết định",
            type: "item",
            url: "/cms/profile/setting/decisioncreate",
            exactMatch: true,
            children: [],
          },
        ],
      },
      {
        id: "cms_profile_list",
        title: "Danh mục",
        translate: "NAV.LIST",
        type: "group",
        icon: "list",
        url: "/cms/profile/list",
        children: [
          {
            id: "position_group",
            title: "Nhóm chức danh",
            translate: "Nhóm chức danh",
            type: "item",
            url: "/cms/profile/list/groupposition",
            exactMatch: true,
            children: [],
          },
          {
            id: "contracttype",
            title: "Loại hợp đồng",
            translate: "Loại hợp đồng",
            type: "item",
            url: "/cms/profile/list/contracttype",
            exactMatch: true,
            children: [],
          },
          {
            id: "welfare",
            title: "Phúc lợi",
            translate: "Phúc lợi",
            type: "item",
            url: "/cms/profile/list/welfare",
            exactMatch: true,
            children: [],
          },
          {
            id: "allowance",
            title: "Phụ cấp",
            translate: "Phụ cấp",
            type: "item",
            url: "/cms/profile/list/allowance",
            exactMatch: true,
            children: [],
          },

          {
            id: "salaryscale",
            title: "Thang lương",
            translate: "Thang lương",
            type: "item",
            url: "/cms/profile/list/salaryscale",
            exactMatch: true,
            children: [],
          },
          {
            id: "salaryrank",
            title: "Ngạch lương",
            translate: "Ngạch lương",
            type: "item",
            url: "/cms/profile/list/salaryrank",
            exactMatch: true,
            children: [],
          },
          {
            id: "salarylevel",
            title: "Bậc lương",
            translate: "Bậc lương",
            type: "item",
            url: "/cms/profile/list/salarylevel",
            exactMatch: true,
            children: [],
          },
          {
            id: "salarytype",
            title: "Bảng lương",
            translate: "Bảng lương",
            type: "item",
            url: "/cms/profile/list/salarytype",
            exactMatch: true,
            children: [],
          },
          {
            id: "salarysample",
            title: "Thang bảng lương",
            translate: "Thang bảng lương",
            type: "item",
            url: "/cms/profile/list/salarysample",
            exactMatch: true,
            children: [],
          },
          {
            id: "profile_list_job-band",
            title: "Danh mục cấp bậc",
            translate: "Danh mục cấp bậc",
            type: "item",
            url: "/cms/profile/list/job-band",
            exactMatch: true,
            children: [],
          },
          {
            id: "otherlist",
            title: "Tham số hệ thống",
            translate: "Tham số hệ thống",
            type: "item",
            url: "/cms/profile/list/otherlist",
            exactMatch: true,
            children: [],
          },
          // {
          //   id: "job",
          //   title: "Danh mục công việc",
          //   translate: "Danh mục công việc",
          //   type: "item",
          //   url: "/cms/profile/list/job",
          //   exactMatch: true,
          // }
        ],
      },
      {
        id: "cms_profile_app",
        title: "Phê duyệt",
        translate: "Phê duyệt",
        type: "group",
        icon: "list",
        url: "/cms/profile/list",
        children: [
          {
            id: "staffprofile-change",
            title: "Thông tin hồ sơ",
            translate: "Thông tin hồ sơ",
            type: "item",
            url: "/cms/profile/business/staffprofile-change",
            exactMatch: true,
            children: [],
          },
          {
            id: "family-change",
            title: "Thông tin Gia cảnh",
            translate: "Thông tin Gia cảnh",
            type: "item",
            url: "/cms/profile/business/family-change",
            exactMatch: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_insurance",
    title: "Bảo hiểm",
    translate: "Bảo hiểm",
    type: "group",
    icon: "home",
    url: "/cms/profile/business/inschange",
    root: true,
    children: [
      {
        id: "cms_insurance_bus",
        title: "NAV.BUSINESS",
        translate: "NAV.BUSINESS",
        type: "group",
        icon: "list",
        url: "/cms/profile/business",
        children: [
          {
            id: "ins_change",
            title: "Biến động bảo hiểm",
            translate: "Biến động bảo hiểm",
            type: "item",
            url: "/cms/profile/business/inschange",
            exactMatch: true, children: [],
          },
          {
            id: "ins_information",
            title: "Thông tin bảo hiểm",
            translate: "Thông tin bảo hiểm",
            type: "item",
            url: "/cms/profile/business/insinformation",
            exactMatch: true, children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_attendance",
    title: "Công",
    translate: "Công",
    type: "group",
    icon: "home",
    url: "/cms/attendance/business/shiftsort",
    root: true,
    children: [
      {
        id: "cms_attendance_bus",
        title: "NAV.BUSINESS",
        translate: "NAV.BUSINESS",
        type: "group",
        icon: "list",
        url: "/cms/attendance/business",
        children: [
          {
            id: "shift_sort",
            title: "Xếp ca làm việc",
            translate: "Xếp ca làm việc",
            type: "item",
            url: "/cms/attendance/business/shiftsort",
            exactMatch: true, children: [],
          },
          {
            id: "duty_sort",
            title: "Xếp ca Trực",
            translate: "Xếp ca Trực",
            type: "item",
            url: "/cms/attendance/business/dutyscheduled",
            exactMatch: true, children: [],
          },
          {
            id: "timesheet",
            title: "Bảng công",
            translate: "Bảng công",
            type: "item",
            url: "/cms/attendance/business/timesheet",
            exactMatch: true, children: [],
          },

          {
            id: "time_late_early",
            title: "Quản lý đi muộn về sớm",
            translate: "Quản lý đi muộn về sớm",
            type: "item",
            url: "/cms/attendance/business/timelateearly",
            exactMatch: true, children: [],
          },
          {
            id: "register_off",
            title: "Quản lý nghỉ phép",
            translate: "Quản lý đăng ký nghỉ",
            type: "item",
            url: "/cms/attendance/business/registeroff",
            exactMatch: true, children: [],
          },
          {
            id: "overtime",
            title: "Quản lý đăng ký OT",
            translate: "Quản lý đăng ký OT",
            type: "item",
            url: "/cms/attendance/business/overtime",
            exactMatch: true, children: [],
          },
          {
            id: "takeleave",
            title: "Quản lý nghỉ phép",
            translate: "Quản lý nghỉ phép",
            type: "item",
            url: "/cms/attendance/business/takeleave",
            exactMatch: true, children: [],
          },
          {
            id: "declareleave",
            title: "Khai báo, điều chỉnh nghỉ phép",
            translate: "Khai báo, điều chỉnh nghỉ phép",
            type: "item",
            url: "/cms/attendance/business/declareleave",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_attendance_setting",
        title: "NAV.SETTING",
        translate: "NAV.SETTING",
        type: "group",
        icon: "list",
        url: "/cms/attendance/setting",
        children: [
          {
            id: "timesheet_formula",
            title: "Công thức tính công",
            translate: "Công thức tính công",
            type: "item",
            url: "/cms/attendance/setting/timesheetformula",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_attendance_list",
        title: "NAV.LIST",
        translate: "NAV.LIST",
        type: "group",
        icon: "list",
        url: "/cms/attendance/list",
        children: [
          {
            id: "symbol",
            title: "Ký hiệu công",
            translate: "Ký hiệu công",
            type: "item",
            url: "/cms/attendance/list/symbol",
            exactMatch: true, children: [],
          },
          {
            id: "timetype",
            title: "Kiểu công",
            translate: "Kiểu công",
            type: "item",
            url: "/cms/attendance/list/timetype",
            exactMatch: true, children: [],
          },
          {
            id: "shift",
            title: "Ca làm việc",
            translate: "Ca làm việc",
            type: "item",
            url: "/cms/attendance/list/shift",
            exactMatch: true, children: [],
          },
          {
            id: "holiday",
            title: "Ngày nghỉ lễ",
            translate: "Ngày nghỉ lễ",
            type: "item",
            url: "/cms/attendance/list/holiday",
            exactMatch: true, children: [],
          },
          {
            id: "salary_period",
            title: "Kỳ công lương",
            translate: "Kỳ công lương",
            type: "item",
            url: "/cms/attendance/list/salaryperiod",
            exactMatch: true, children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_payroll",
    title: "Lương",
    translate: "Lương",
    type: "group",
    icon: "home",
    url: "/cms/payroll/business/calculatepayroll",
    root: true,
    children: [
      {
        id: "cms_profile_bus",
        title: "NAV.BUSINESS",
        translate: "NAV.BUSINESS",
        type: "group",
        icon: "list",
        url: "/cms/profile/business",
        children: [
          {
            id: "importpayroll",
            title: "Import lương",
            translate: "Import lương",
            type: "item",
            url: "/cms/payroll/business/importpayroll",
            exactMatch: true, children: [],
          },
          {
            id: "advance",
            title: "Tạm ứng lương",
            translate: "Tạm ứng lương",
            type: "item",
            url: "/cms/payroll/business/advance",
            exactMatch: true, children: [],
          },
          {
            id: "kpiemployee",
            title: "Tính lương KPI",
            translate: "Tính lương KPI",
            type: "item",
            url: "/cms/payroll/business/kpiemployee",
            exactMatch: true, children: [],
          },
          {
            id: "payroll_salaryelement",
            title: "Tính lương",
            translate: "Tính lương",
            type: "item",
            url: "/cms/payroll/business/calculatepayroll",
            exactMatch: true, children: [],
          },
          {
            id: "importproduct",
            title: "Import sản phẩm",
            translate: "Import sản phẩm",
            type: "item",
            url: "/cms/payroll/business/importproduct",
            exactMatch: true, children: [],
          },
          {
            id: "importmachines",
            title: "Import khuôn theo máy uốn",
            translate: "Import khuôn theo máy uốn",
            type: "item",
            url: "/cms/payroll/business/importmachines",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_profile_setting",
        title: "NAV.SETTING",
        translate: "NAV.SETTING",
        type: "group",
        icon: "list",
        url: "/cms/profile/setting",
        children: [
          {
            id: "payroll_formula",
            title: "Công thức tính lương",
            translate: "Công thức tính lương",
            type: "item",
            url: "/cms/payroll/setting/payrollformula",
            exactMatch: true, children: [],
          },
          {
            id: "kpiformula",
            title: "Công thức KPI",
            translate: "Công thức KPI",
            type: "item",
            url: "/cms/payroll/setting/kpiformula",
            exactMatch: true, children: [],
          },
          {
            id: "kpiposition",
            title: "Thiết lập KPI theo chức vụ",
            translate: "Thiết lập KPI theo chức vụ",
            type: "item",
            url: "/cms/payroll/setting/kpiposition",
            exactMatch: true, children: [],
          },
          {
            id: "paycheck",
            title: "Phiếu lương",
            translate: "Phiếu lương",
            type: "item",
            url: "/cms/payroll/setting/paycheck",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_payroll_list",
        title: "NAV.LIST",
        translate: "NAV.LIST",
        type: "group",
        icon: "list",
        url: "/cms/payroll/list",
        children: [
          {
            id: "salary_element",
            title: "Phần tử lương",
            translate: "Phần tử lương",
            type: "item",
            url: "/cms/payroll/list/salaryelement",
            exactMatch: true, children: [],
          },
          {
            id: "salary_structure",
            title: "Thông tin kết cấu bảng lương",
            translate: "Thông tin kết cấu bảng lương",
            type: "item",
            url: "/cms/payroll/list/salarystructure",
            exactMatch: true, children: [],
          },
          {
            id: "kpigroup",
            title: "Nhóm phần tử KPI",
            translate: "Nhóm phần tử KPI",
            type: "item",
            url: "/cms/payroll/list/kpigroup",
            exactMatch: true, children: [],
          },
          {
            id: "kpitarget",
            title: "Phần tử KPI",
            translate: "Phần tử KPI",
            type: "item",
            url: "/cms/payroll/list/kpitarget",
            exactMatch: true, children: [],
          },
          {
            id: "listmachine",
            title: "Danh mục máy uốn",
            translate: "Danh mục máy uốn",
            type: "item",
            url: "/cms/payroll/list/listmachine",
            exactMatch: true, children: [],
          },
          {
            id: "listproduct",
            title: "Danh mục sản phẩm",
            translate: "Danh mục sản phẩm",
            type: "item",
            url: "/cms/payroll/list/listproduct",
            exactMatch: true, children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_dashboard",
    title: "Báo cáo",
    translate: "Báo cáo",
    type: "group",
    icon: "home",
    url: "/cms/dashboard",
    root: true,
    children: [
      {
        id: "cms_dashbord_bus",
        title: "NAV.BUSINESS",
        translate: "NAV.BUSINESS",
        type: "group",
        icon: "list",
        url: "/cms/report/business",
        children: [
          {
            id: "report-management",
            title: "Báo cáo",
            translate: "Báo cáo",
            type: "item",
            url: "/cms/report/business/businessreport",
            exactMatch: true, children: [],
          },
          {
            id: "report-business",
            title: "Báo cáo quản trị",
            translate: "Báo cáo quản trị",
            type: "item",
            url: "/cms/report/business/reportchart",
            exactMatch: true, children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_system",
    title: "Hệ thống",
    translate: "Hệ thống",
    type: "group",
    icon: "gear",
    url: "/cms/system",
    children: [
      {
        id: "sys_groupuser",
        title: "Nhóm tài khoản",
        translate: "Nhóm tài khoản",
        type: "item",
        url: "/cms/system/groupuser",
        exactMatch: true, children: [],
      },
      {
        id: "sys_user",
        title: "Tài khoản",
        translate: "Tài khoản",
        type: "item",
        url: "/cms/system/user",
        exactMatch: true, children: [],
      },
      {
        id: "sys_groupuser_permission",
        title: "Phân quyền nhóm tài khoản",
        translate: "Phân quyền nhóm tài khoản",
        type: "item",
        url: "/cms/system/grouppermission",
        exactMatch: true, children: [],
      },
      {
        id: "sys_user_permission",
        title: "Phân quyền Tài khoản",
        translate: "Phân quyền Tài khoản",
        type: "item",
        url: "/cms/system/upermission",
        exactMatch: true, children: [],
      },
      {
        id: "sys_report",
        title: "Thiết lập biểu mẫu",
        translate: "Thiết lập biểu mẫu",
        type: "item",
        url: "/cms/system/settingreport",
        exactMatch: true, children: [],
      },
      {
        id: "sys_settingremind",
        title: "Thiết lập hệ thống",
        translate: "Thiết lập hệ thống",
        type: "item",
        url: "/cms/system/settingremind",
        exactMatch: true, children: [],
      },
      {
        id: "settingmap",
        title: "Thiết lập địa điểm chấm công",
        translate: "Thiết lập địa điểm chấm công",
        type: "item",
        url: "/cms/system/settingmap",
        exactMatch: true, children: [],
      },
      {
        id: "sys_approveprocess",
        title: "Thiết lập quy trình phê duyệt",
        translate: "Thiết lập quy trình phê duyệt",
        type: "item",
        url: "/cms/system/approveprocess",
        exactMatch: true, children: [],
      },
      {
        id: "sys_approvetemplate",
        title: "Thiết lập Template phê duyệt",
        translate: "Thiết lập Template phê duyệt",
        type: "item",
        url: "/cms/system/approvetemplate",
        exactMatch: true,
        children: [],
      }
    ],
    root: true,
  },
  {
    id: "cms_administration",
    title: "Hành chính",
    translate: "Hành chính",
    type: "group",
    icon: "home",
    url: "/cms/administration",
    root: true,
    children: [
      {
        id: "cms_administration_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        children: [
          {
            id: "room",
            title: "Phòng họp",
            translate: "Phòng họp",
            type: "item",
            url: "/cms/administration/list/room",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        children: [
          {
            id: "booking",
            title: "Đặt phòng họp",
            translate: "Đặt phòng họp",
            type: "item",
            url: "/cms/administration/business/booking",
            exactMatch: true, children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_internalblog",
    title: "Truyền thông",
    translate: "Truyền thông",
    type: "group",
    icon: "home",
    url: "/cms/media/internalblog",
    root: true,
    children: [
      {
        id: "cms-app-internalblog",
        title: "Tin tức nội bộ",
        translate: "Tin tức nội bộ",
        type: "item",
        url: "/cms/media/internalblog",
        exactMatch: true, children: [],
      },
      {
        id: "cms-app-survey",
        title: "Thông tin cuộc khảo sát",
        translate: "Thông tin cuộc khảo sát",
        type: "item",
        url: "/cms/media/survey",
        exactMatch: true, children: [],
      },
    ],
  },
  // {
  //   id: "others",
  //   title: "Khác",
  //   translate: "Khác",
  //   type: "group",
  //   icon: "home",
  //   url: "/cms/others",
  //   root: true,
  //   children: [
  //     {
  //       id: "payroll3P",
  //       title: "Lương 3P",
  //       translate: "Lương 3P",
  //       type: "group",
  //       icon: "home",
  //       url: "/cms/others/payroll3p",
  //       exactMatch: true,
  //       children: [
  //         {
  //           id: "payroll3Plist",
  //           title: "Danh mục",
  //           translate: "Danh mục",
  //           type: "group",
  //           icon: "home",
  //           url: "/cms/others/payroll3p/payroll3plist",
  //           exactMatch: true,
  //           children: [
  //             {
  //               id: "competence",
  //               title: "Nhóm năng lực cá nhân",
  //               translate: "Nhóm năng lực cá nhân",
  //               type: "item",
  //               url: "/cms/others/payroll3p/payroll3plist/competence",
  //               exactMatch: true
  //             },
  //             {
  //               id: "leveldetails",
  //               title: "Năng lực cá nhân",
  //               translate: "Năng lực cá nhân",
  //               type: "item",
  //               url: "/cms/others/payroll3p/payroll3plist/leveldetails",
  //               exactMatch: true
  //             },
  //             {
  //               id: "jobevalue",
  //               title: "Năng lực vị trí",
  //               translate: "Năng lực vị trí",
  //               type: "item",
  //               url: "/cms/others/payroll3p/payroll3plist/jobevaluetion",
  //               exactMatch: true
  //             },
  //             {
  //               id: "exchangelist",
  //               title: "Quy đổi bậc lương",
  //               translate: "Quy đổi bậc lương",
  //               type: "item",
  //               url: "/cms/others/payroll3p/payroll3plist/exchangelist",
  //               exactMatch: true
  //             }
  //           ],
  //         },
  //         {
  //           id: "config3p",
  //           title: "Thiết lập",
  //           translate: "Thiết lập",
  //           type: "group",
  //           icon: "home",
  //           url: "/cms/others/payroll3p/config3p",
  //           exactMatch: true,
  //           children: [
  //             {
  //               id: "jobevaluetionconfig",
  //               title: "Năng lực vị trí",
  //               translate: "Năng lực vị trí",
  //               type: "item",
  //               url: "/cms/others/payroll3p/config3p/jobevaluetionconfig",
  //               exactMatch: true
  //             },
  //             {
  //               id: "personcompetence",
  //               title: "Năng lực cá nhân",
  //               translate: "Năng lực cá nhân",
  //               type: "item",
  //               url: "/cms/others/payroll3p/config3p/personcompetence",
  //               exactMatch: true
  //             },
  //             {
  //               id: "unitprice",
  //               title: "Đơn giá",
  //               translate: "Đơn giá",
  //               type: "item",
  //               url: "/cms/others/payroll3p/config3p/unitprice",
  //               exactMatch: true
  //             },
  //             {
  //               id: "ranksystem",
  //               title: "Hệ thống thang bậc lương",
  //               translate: "Hệ thống thang bậc lương",
  //               type: "item",
  //               url: "/cms/others/payroll3p/config3p/ranksystem",
  //               exactMatch: true
  //             },
  //             {
  //               id: "groupposition3p",
  //               title: "Phân nhóm chức năng",
  //               translate: "Phân nhóm chức năng",
  //               type: "item",
  //               url: "/cms/others/payroll3p/config3p/groupposition3p",
  //               exactMatch: true
  //             }
  //           ],
  //         }
  //       ],
  //     }
  //   ],
  // },
];

