export enum EnumCoreFormControlSeekerSourceType {
    EMPLOYEE_SEEK = "EMPLOYEE_SEEK",
    CONTRACT_SEEK = "CONTRACT_SEEK",
    WORKING_SEEK = "WORKING_SEEK",
    WAGE_SEEK = "WAGE_SEEK",
    POSITION_SEEK = "POSITION_SEEK",
    POSITION_CONCURRENT_SEEK = "POSITION_CONCURRENT_SEEK",
    ORGANIZATION_UNIT_SEEK = "ORGANIZATION_UNIT_SEEK",
}